In [1]:
import numpy as np

In [2]:
np.array([4,5,6,3,4,6,7,8,9,3])

array([4, 5, 6, 3, 4, 6, 7, 8, 9, 3])

In [3]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
# by default returns 50 elements in a given range
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [6]:
np.linspace(1,10, num=20,retstep=True)

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# be default we will get a random number b/w 0 to 1
np.random.random()

0.671030122641688

In [14]:
np.random.random(size=(4,4))

array([[0.65067082, 0.77375346, 0.59868135, 0.818304  ],
       [0.8597723 , 0.76024623, 0.71801525, 0.00960911],
       [0.20343428, 0.99956928, 0.20391454, 0.08121303],
       [0.53980171, 0.93959944, 0.93262496, 0.96211545]])

In [20]:
np.random.randint(1,10)

6

In [21]:
np.random.randint(1,10,6)

array([9, 2, 8, 4, 6, 8])

In [22]:
np.random.randint(1,10,(6,4))

array([[5, 9, 2, 4],
       [7, 7, 7, 2],
       [8, 9, 7, 2],
       [6, 4, 4, 3],
       [4, 3, 9, 4],
       [2, 7, 2, 3]])

In [23]:
x = np.random.randint(1,10,(6,4))

In [24]:
x

array([[7, 8, 1, 8],
       [3, 7, 6, 8],
       [5, 4, 9, 6],
       [1, 6, 7, 3],
       [9, 2, 9, 2],
       [8, 4, 1, 1]])

In [25]:
x[0]

array([7, 8, 1, 8])

In [26]:
x[1]

array([3, 7, 6, 8])

In [27]:
x[0:3]

array([[7, 8, 1, 8],
       [3, 7, 6, 8],
       [5, 4, 9, 6]])

In [29]:
x[0:3,0:2]

array([[7, 8],
       [3, 7],
       [5, 4]])

In [30]:
x[:,0:2]

array([[7, 8],
       [3, 7],
       [5, 4],
       [1, 6],
       [9, 2],
       [8, 4]])

In [31]:
x.shape

(6, 4)

In [33]:
x[3][1]

6

In [34]:
# transpose
x.T

array([[7, 3, 5, 1, 9, 8],
       [8, 7, 4, 6, 2, 4],
       [1, 6, 9, 7, 9, 1],
       [8, 8, 6, 3, 2, 1]])

In [35]:
x.reshape((8,3))

array([[7, 8, 1],
       [8, 3, 7],
       [6, 8, 5],
       [4, 9, 6],
       [1, 6, 7],
       [3, 9, 2],
       [9, 2, 8],
       [4, 1, 1]])

In [37]:
x.reshape((3,8))

array([[7, 8, 1, 8, 3, 7, 6, 8],
       [5, 4, 9, 6, 1, 6, 7, 3],
       [9, 2, 9, 2, 8, 4, 1, 1]])

In [38]:
x.reshape((2,-1))

array([[7, 8, 1, 8, 3, 7, 6, 8, 5, 4, 9, 6],
       [1, 6, 7, 3, 9, 2, 9, 2, 8, 4, 1, 1]])

In [39]:
x.reshape((-1,12))

array([[7, 8, 1, 8, 3, 7, 6, 8, 5, 4, 9, 6],
       [1, 6, 7, 3, 9, 2, 9, 2, 8, 4, 1, 1]])

In [40]:
# convert 2D to 1D
x.flatten()

array([7, 8, 1, 8, 3, 7, 6, 8, 5, 4, 9, 6, 1, 6, 7, 3, 9, 2, 9, 2, 8, 4,
       1, 1])

In [41]:
y = x.flatten()

In [42]:
y

array([7, 8, 1, 8, 3, 7, 6, 8, 5, 4, 9, 6, 1, 6, 7, 3, 9, 2, 9, 2, 8, 4,
       1, 1])

In [43]:
np.mean(y)

5.208333333333333

In [44]:
np.median(y)

6.0

In [45]:
np.max(y)

9

In [46]:
np.argmax(y)

10

In [51]:
np.sort(y,kind='heapsort')

array([1, 1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9,
       9, 9])

In [48]:
np.mean(x)

5.208333333333333

In [50]:
np.mean(x, axis=1)

array([6.  , 6.  , 6.  , 4.25, 5.5 , 3.5 ])